# Generated by Django 3.0.3 on 2020-04-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depository',
            fields=[
                ('ID', models.IntegerField(verbose_name='游戏ID')),
                ('Link', models.CharField(max_length=100, verbose_name='游戏链接')),
                ('GameName', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='游戏名称')),
                ('BundleBaseDiscount', models.CharField(max_length=20, verbose_name='基本折扣力度')),
                ('DiscountPct', models.CharField(max_length=20, verbose_name='现有折扣力度')),
                ('OriginalPrice', models.CharField(max_length=20, verbose_name='原价')),
                ('FinalPrice', models.CharField(max_length=20, verbose_name='现价')),
                ('LowestPrice', models.CharField(max_length=20, verbose_name='史低')),
                ('LastPrice', models.CharField(max_length=20, verbose_name='上次价格')),
                ('IfHandle', models.BooleanField(verbose_name='是否处理')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorCheck',
            fields=[
                ('ID', models.IntegerField(verbose_name='游戏ID')),
                ('Link', models.CharField(max_length=100, verbose_name='游戏链接')),
                ('GameName', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='游戏名称')),
                ('BundleBaseDiscount', models.CharField(max_length=20, verbose_name='基本折扣力度')),
                ('DiscountPct', models.CharField(max_length=20, verbose_name='现有折扣力度')),
                ('OriginalPrice', models.CharField(max_length=20, verbose_name='原价')),
                ('FinalPrice', models.CharField(max_length=20, verbose_name='现价')),
                ('LowestPrice', models.CharField(max_length=20, verbose_name='史低')),
                ('LastPrice', models.CharField(max_length=20, verbose_name='上次价格')),
                ('IfHandle', models.BooleanField(verbose_name='是否处理')),
            ],
        ),
    ]
