# Generated by Django 3.0.3 on 2020-04-24 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SteamGames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_notified', models.BooleanField(verbose_name='是否通知过')),
                ('steam_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SteamGames.Depository', verbose_name='订阅游戏')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('web_openid', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='openid')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('c_time', models.DateTimeField()),
                ('has_confirmed', models.BooleanField(default=False)),
                ('steam_games_subscribed', models.ManyToManyField(through='GameCrawler.SteamSubscriber', to='SteamGames.Depository')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddField(
            model_name='steamsubscriber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameCrawler.User', verbose_name='订阅用户'),
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GameCrawler.User')),
            ],
            options={
                'verbose_name': '确认码',
                'verbose_name_plural': '确认码',
                'ordering': ['-c_time'],
            },
        ),
    ]
