# Generated by Django 3.0.3 on 2020-04-24 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SteamGames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatUser',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='昵称')),
                ('wechat_openid', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='openid')),
                ('password', models.CharField(max_length=200, null=True, verbose_name='密码')),
                ('is_effective', models.BooleanField(default=True)),
                ('c_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': '微信用户',
                'verbose_name_plural': '微信用户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='wx_SteamSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_notified', models.BooleanField(verbose_name='是否通知过')),
                ('steam_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SteamGames.Depository', verbose_name='订阅游戏')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wechat.WechatUser', verbose_name='订阅用户')),
            ],
        ),
        migrations.AddField(
            model_name='wechatuser',
            name='steam_games_subscribed',
            field=models.ManyToManyField(through='Wechat.wx_SteamSubscriber', to='SteamGames.Depository'),
        ),
    ]
